
PUT /api/sentiment/trainer HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{ "value": "test", "category": -2, "weight" : 1 }

POST /api/sentiment/classification HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
	"text":"My brother hate java"
}

GET /api/tweets/fsharp HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache
